version: '3'
services:
  mysql:
    image: mysql:8.0 # Usa la imagen oficial si no necesitas un Dockerfile personalizado
    environment:
      MYSQL_ROOT_PASSWORD: enarm_db
      MYSQL_DATABASE: enarm_db
    volumes:
      - "./mysql_data:/var/lib/mysql" # Ruta local relativa para evitar problemas en Windows
    ports:
      - "3306:3306"
    networks:
      - my_custom_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      timeout: 20s
      retries: 10

networks:
  my_custom_network:
    external: true